// Code generated by gocallgen. DO NOT EDIT.
package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"gopkg.d7z.net/cdp/internal/binding"
)

const goCallBindingName = "__cdp_ffi_binding_bind_6WReiXstPwTlaXA4BU9LNF"
const goCallDeliverySlotName = "__cdp_ffi_slot_bind_6WReiXstPwTlaXA4BU9LNF"

type goCallPayload struct {
	Kind       string   `json:"kind"`
	SessionKey string   `json:"sessionKey"`
	CallID     string   `json:"callId"`
	FuncName   string   `json:"funcName"`
	TimeoutMS  int      `json:"timeoutMs"`
	Args       []string `json:"args"`
}

type goCallResult struct {
	SessionKey string `json:"sessionKey"`
	CallID     string `json:"callId"`
	OK         bool   `json:"ok"`
	Result     any    `json:"result,omitempty"`
	Error      string `json:"error,omitempty"`
}

type goCallAPI interface {
	CoreRuntimeReady(GoCallContext, bool)
	FullscreenState(GoCallContext, bool, string) error
	OnFocus(GoCallContext) error
	PageID(GoCallContext) (string, error)
}

type CallCoreBinding struct {
	FFI      CallCore
	requests *sync.Map
}

func NewCallCoreBinding() CallCoreBinding {
	return CallCoreBinding{FFI: CallCore{}, requests: &sync.Map{}}
}

func (CallCoreBinding) Name() string {
	return goCallBindingName
}

func handleGoCallPayload(api goCallAPI, requests *sync.Map, ctx BindingContext, rawPayload string) error {
	p := ctx.Page
	executionContextID := ctx.ExecutionContextID
	var payload goCallPayload
	if err := json.Unmarshal([]byte(rawPayload), &payload); err != nil {
		return fmt.Errorf("parse go call payload: %w", err)
	}
	requestKey := payload.SessionKey + "\x00" + payload.CallID
	if payload.Kind == "cancel" {
		if cancelValue, ok := requests.LoadAndDelete(requestKey); ok {
			cancelValue.(context.CancelFunc)()
		}
		return nil
	}
	if ctx.Context == nil {
		ctx.Context = p
	}
	if payload.Kind == "request" {
		timeout := time.Duration(payload.TimeoutMS) * time.Millisecond
		if timeout <= 0 {
			timeout = 30 * time.Second
		}
		requestCtx, cancel := context.WithTimeout(ctx.Context, timeout)
		ctx.Context = requestCtx
		requests.Store(requestKey, context.CancelFunc(cancel))
		defer func() { requests.Delete(requestKey); cancel() }()
	}
	value, err := dispatchGoCall(api, ctx, payload)
	if payload.Kind != "request" {
		return err
	}
	if payload.SessionKey == "" || payload.CallID == "" {
		return fmt.Errorf("request %s missing session key or call id", payload.FuncName)
	}
	resultPayload := goCallResult{SessionKey: payload.SessionKey, CallID: payload.CallID, OK: err == nil}
	if err != nil {
		resultPayload.Error = err.Error()
	} else {
		resultPayload.Result = value
	}
	marshal, marshalErr := json.Marshal(resultPayload)
	if marshalErr != nil {
		return fmt.Errorf("marshal go call result %s: %w", payload.FuncName, marshalErr)
	}
	handled, deliverErr := p.DeliverBindingResultInSessionContext(ctx.Context, ctx.SessionID, executionContextID, goCallDeliverySlotName, payload.SessionKey, string(marshal))
	if deliverErr != nil {
		return fmt.Errorf("deliver go call result func=%s call_id=%s: %w", payload.FuncName, payload.CallID, deliverErr)
	}
	if !handled {
		return nil
	}
	return nil
}

func (b CallCoreBinding) Handle(ctx BindingContext, data *binding.BindingCalledEvent) error {
	if b.requests == nil {
		b.requests = &sync.Map{}
	}
	return handleGoCallPayload(b.FFI, b.requests, ctx, data.Payload)
}

func dispatchGoCall(api goCallAPI, ctx BindingContext, payload goCallPayload) (any, error) {
	p := ctx.Page
	manager := ctx.Manager
	switch payload.FuncName {
	case "coreRuntimeReady":
		if payload.Kind != "notify" {
			return nil, fmt.Errorf("coreRuntimeReady requires notify call mode, got %s", payload.Kind)
		}
		if len(payload.Args) != 1 {
			return nil, fmt.Errorf("coreRuntimeReady expects 1 args, got %d", len(payload.Args))
		}
		var arg0 bool
		if err := json.Unmarshal([]byte(payload.Args[0]), &arg0); err != nil {
			return nil, fmt.Errorf("decode coreRuntimeReady arg top: %w", err)
		}
		api.CoreRuntimeReady(GoCallContext{Context: ctx.Context, Page: p, Manager: manager, SessionID: ctx.SessionID, TargetID: ctx.TargetID, TargetType: ctx.TargetType, ExecutionContextID: ctx.ExecutionContextID}, arg0)
		return nil, nil
	case "fullscreenState":
		if payload.Kind != "notify" {
			return nil, fmt.Errorf("fullscreenState requires notify call mode, got %s", payload.Kind)
		}
		if len(payload.Args) != 2 {
			return nil, fmt.Errorf("fullscreenState expects 2 args, got %d", len(payload.Args))
		}
		var arg0 bool
		if err := json.Unmarshal([]byte(payload.Args[0]), &arg0); err != nil {
			return nil, fmt.Errorf("decode fullscreenState arg active: %w", err)
		}
		var arg1 string
		if err := json.Unmarshal([]byte(payload.Args[1]), &arg1); err != nil {
			return nil, fmt.Errorf("decode fullscreenState arg element: %w", err)
		}
		return nil, api.FullscreenState(GoCallContext{Context: ctx.Context, Page: p, Manager: manager, SessionID: ctx.SessionID, TargetID: ctx.TargetID, TargetType: ctx.TargetType, ExecutionContextID: ctx.ExecutionContextID}, arg0, arg1)
	case "onFocus":
		if payload.Kind != "notify" {
			return nil, fmt.Errorf("onFocus requires notify call mode, got %s", payload.Kind)
		}
		if len(payload.Args) != 0 {
			return nil, fmt.Errorf("onFocus expects 0 args, got %d", len(payload.Args))
		}
		return nil, api.OnFocus(GoCallContext{Context: ctx.Context, Page: p, Manager: manager, SessionID: ctx.SessionID, TargetID: ctx.TargetID, TargetType: ctx.TargetType, ExecutionContextID: ctx.ExecutionContextID})
	case "pageId":
		if payload.Kind != "request" {
			return nil, fmt.Errorf("pageId requires request call mode, got %s", payload.Kind)
		}
		if len(payload.Args) != 0 {
			return nil, fmt.Errorf("pageId expects 0 args, got %d", len(payload.Args))
		}
		return api.PageID(GoCallContext{Context: ctx.Context, Page: p, Manager: manager, SessionID: ctx.SessionID, TargetID: ctx.TargetID, TargetType: ctx.TargetType, ExecutionContextID: ctx.ExecutionContextID})
	default:
		return nil, fmt.Errorf("unknown go call func: %s", payload.FuncName)
	}
}
