package engine

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"unicode"
)

type RuntimeFieldSet struct {
	MainRuntime       string
	ScriptLabel       string
	FrameTransportKey string
}

const randomFieldAlphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

var runtimeFieldForbiddenTokens = []string{"cdp", "ffi", "helper", "runtime"}

func newRuntimeFieldSet() (RuntimeFieldSet, error) {
	mainRuntime, err := newRuntimeFieldName()
	if err != nil {
		return RuntimeFieldSet{}, err
	}
	scriptLabel, err := newRuntimeFieldName()
	if err != nil {
		return RuntimeFieldSet{}, err
	}
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return RuntimeFieldSet{}, err
	}
	return RuntimeFieldSet{
		MainRuntime:       mainRuntime,
		ScriptLabel:       scriptLabel,
		FrameTransportKey: hex.EncodeToString(key),
	}, nil
}

func newRuntimeFieldName() (string, error) {
	const fieldLen = 22
	raw := make([]byte, fieldLen)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	var b strings.Builder
	b.Grow(fieldLen + 1)
	b.WriteByte('_')
	for _, v := range raw {
		b.WriteByte(randomFieldAlphabet[int(v)%len(randomFieldAlphabet)])
	}
	value := b.String()
	if runtimeFieldNameHasForbiddenToken(value) {
		return newRuntimeFieldName()
	}
	return value, nil
}

func runtimeFieldNameHasForbiddenToken(value string) bool {
	value = strings.ToLower(value)
	for _, token := range runtimeFieldForbiddenTokens {
		if strings.Contains(value, token) {
			return true
		}
	}
	return false
}

func renderMainWorldScript(script string, fields RuntimeFieldSet) string {
	script = strings.ReplaceAll(script, "__MAIN_RUNTIME_SLOT__", fields.MainRuntime)
	return script
}

func mainRuntimeMethodCall(fieldName string, method string) (string, error) {
	fieldName = strings.TrimSpace(fieldName)
	if !isJSIdentifierName(fieldName) {
		return "", errors.New("main runtime field is empty")
	}
	parts, err := splitMainRuntimeMethod(method)
	if err != nil {
		return "", err
	}
	receiver := "rt"
	if len(parts) > 1 {
		receiver = "rt?." + strings.Join(parts[:len(parts)-1], "?.")
	}
	fn := "receiver?." + parts[len(parts)-1]
	return `(() => {
	const rt = typeof ` + fieldName + ` === "undefined" ? undefined : ` + fieldName + `;
	const receiver = ` + receiver + `;
	const fn = ` + fn + `;
	if (typeof fn !== "function") {
		return undefined;
	}
	return fn.call(receiver);
})()`, nil
}

func splitMainRuntimeMethod(method string) ([]string, error) {
	parts := strings.Split(method, ".")
	if len(parts) == 0 {
		return nil, errors.New("main runtime method is empty")
	}
	for _, part := range parts {
		if !isJSIdentifierName(part) {
			return nil, fmt.Errorf("invalid main runtime method %q", method)
		}
	}
	return parts, nil
}

func isJSIdentifierName(value string) bool {
	if value == "" {
		return false
	}
	for i, r := range value {
		if i == 0 {
			if r != '_' && r != '$' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && r != '$' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

// Main-world controllers live in a global lexical binding, not on Window.
// The identifier is generated by Go and is never exposed through page hooks.
func mainWorldInstallSource(source, name string) string {
	return "let " + name + " = (() => { let control; const __INSTALL_MAIN_CONTROL__ = value => { control = value; };\n" + source + "\nreturn control; })();"
}

func renderCoreScript(source string, fields RuntimeFieldSet) string {
	return strings.ReplaceAll(source, "__FRAME_TRANSPORT_KEY__", fields.FrameTransportKey)
}
