/**
 * @generated by gocallgen. DO NOT EDIT.
 */

const goCallBindingName = "__cdp_ffi_binding_bind_6WReiXstPwTlaXA4BU9LNF";
const goCallDeliverySlotName = "__cdp_ffi_slot_bind_6WReiXstPwTlaXA4BU9LNF";

type PendingCall = {
    resolve: (value: any) => void;
    reject: (error: Error) => void;
    timeoutId: ReturnType<typeof setTimeout>;
};

type GoCallResultPayload = {
    sessionKey: string;
    callId: string;
    ok: boolean;
    result?: unknown;
    error?: string;
};

type GoCallChannel = {
    sessionKey: string;
    pending: Map<string, PendingCall>;
    destroyed: boolean;
    deliver: (rawPayload: string) => boolean;
    invalidate: (reason?: string) => void;
};

function randomKey(prefix: string): string {
    return `${prefix}${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`;
}

function globalStore(): Record<string, unknown> {
    return globalThis as unknown as Record<string, unknown>;
}

function setHiddenGlobal(name: string, value: unknown): void {
    Object.defineProperty(globalThis, name, {
        value,
        writable: true,
        configurable: true,
        enumerable: false,
    });
}

function channelError(message: string): Error {
    return new Error(`[CDP] ${message}`);
}

function isChannel(value: unknown): value is GoCallChannel {
    if (!value || typeof value !== "object") {
        return false;
    }
    const candidate = value as Partial<GoCallChannel>;
    return typeof candidate.sessionKey === "string" && candidate.pending instanceof Map && typeof candidate.deliver === "function" && typeof candidate.invalidate === "function";
}

function createChannel(): GoCallChannel {
    const store = globalStore();
    const previous = store[goCallDeliverySlotName];
    if (isChannel(previous)) {
        previous.invalidate("session replaced");
    }
    const sessionKey = randomKey(`${goCallDeliverySlotName}__session_`);
    const pending = new Map<string, PendingCall>();
    const channel: GoCallChannel = {
        sessionKey,
        pending,
        destroyed: false,
        deliver: (rawPayload: string) => {
            let payload: GoCallResultPayload;
            try {
                payload = JSON.parse(rawPayload) as GoCallResultPayload;
            } catch (_err) {
                return false;
            }
            if (payload.sessionKey !== sessionKey) {
                return false;
            }
            const current = pending.get(payload.callId);
            if (!current) {
                return true;
            }
            clearTimeout(current.timeoutId);
            pending.delete(payload.callId);
            if (payload.ok) {
                current.resolve(payload.result);
            } else {
                current.reject(channelError(payload.error || "go call failed"));
            }
            return true;
        },
        invalidate: (reason?: string) => {
            if (channel.destroyed) {
                return;
            }
            channel.destroyed = true;
            for (const [callId, current] of pending.entries()) {
                clearTimeout(current.timeoutId);
                const binding = store[goCallBindingName];
                if (typeof binding === "function") binding(JSON.stringify({kind: "cancel", sessionKey, callId}));
                current.reject(channelError(reason ? `session invalidated: ${reason}` : `session invalidated (${callId})`));
            }
            pending.clear();
            if (store[goCallDeliverySlotName] === channel) {
                delete store[goCallDeliverySlotName];
            }
        },
    };
    setHiddenGlobal(goCallDeliverySlotName, channel);
    return channel;
}

function ensureChannel(): GoCallChannel {
    const existing = globalStore()[goCallDeliverySlotName];
    if (isChannel(existing) && !existing.destroyed) {
        return existing;
    }
    return createChannel();
}

function getBinding(funcName: string): (payload: string) => void {
    const binding = globalStore()[goCallBindingName];
    if (typeof binding !== "function") {
        throw channelError(`window.${goCallBindingName} not found for ${funcName}`);
    }
    return binding as (payload: string) => void;
}

function notify(funcName: string, ...args: unknown[]): void {
    const channel = ensureChannel();
    const binding = getBinding(funcName);
    binding(JSON.stringify({
        kind: "notify",
        sessionKey: channel.sessionKey,
        funcName,
        args: args.map((arg: unknown) => JSON.stringify(arg)),
    }));
}

function request<T>(funcName: string, ...args: unknown[]): Promise<T> {
    const channel = ensureChannel();
    const binding = getBinding(funcName);
    const callId = randomKey(`${goCallBindingName}__result_`);
    return new Promise<T>((resolve, reject) => {
        const timeoutId = setTimeout(() => {
            channel.pending.delete(callId);
            try { binding(JSON.stringify({kind: "cancel", sessionKey: channel.sessionKey, callId})); } catch (_err) {}
            reject(channelError(`Call to ${funcName} timed out`));
        }, 30000);
        channel.pending.set(callId, { resolve, reject, timeoutId });
        try {
            binding(JSON.stringify({
                kind: "request",
                sessionKey: channel.sessionKey,
                callId,
                timeoutMs: 30000,
                funcName,
                args: args.map((arg: unknown) => JSON.stringify(arg)),
            }));
        } catch (err) {
            clearTimeout(timeoutId);
            channel.pending.delete(callId);
            reject(err instanceof Error ? err : channelError(String(err)));
        }
    });
}

export class CallCore {
    destroy(): void {
        const existing = globalStore()[goCallDeliverySlotName];
        if (isChannel(existing)) {
            existing.invalidate("destroy");
        }
    }

    coreRuntimeReady(top: boolean): void {
        notify("coreRuntimeReady", top);
    }

    fullscreenState(active: boolean, element: string): void {
        notify("fullscreenState", active, element);
    }

    onFocus(): void {
        notify("onFocus");
    }

    async pageId(): Promise<string> {
        return await request<string>("pageId");
    }

}
